---
  - name: copy deploy key to server
    copy: src=deploy_key dest=/home/ubuntu/.ssh/ owner=ubuntu group=ubuntu mode=0600

  - name: install packages
    apt: name={{ item }} state=present update_cache=yes
    with_items:
      - git
      - python-pip

  - name: install docker
    shell: curl -sSL https://get.docker.com/ | sh
    args:
      creates: /usr/bin/docker
    notify:
      - start docker engine

  - name: pip install docker-py
    pip: name=docker-py

  - name: clone repo
    git: repo=git@github.com:austiine04/pneuma.git
         dest=/srv/checkout
         key_file=/home/ubuntu/.ssh/deploy_key
         accept_hostkey=True

  - name: add .env file
    template: src=env.j2 dest=/srv/checkout/.env owner=www-data mode=0744

  - name: build docker image
    docker_image: path=/srv/checkout name="pneuma/pneuma" state=build

  - name: stop container if one currently exists
    docker: name="pneuma" image="pneuma/pneuma" command="/sbin/my_init --" state=absent

  - name: create a directory for postgres data
    file: path=/data state=directory

  - name: start the new shiny container
    docker:
      name: pneuma
      image: pneuma/pneuma
      state: started
      ports:
        - "80:80"
      volumes:
        - /data:/var/lib/postgres/9.3/main

  - name: clean up the checkout directory
    shell: rm -rf /srv/checkout
